# Generated by Django 6.0.3 on 2026-03-04 07:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('steps', models.JSONField(default=list)),
                ('roles_autorises', models.JSONField(default=list)),
                ('delai_maximum', models.IntegerField(help_text='Délai maximum en jours')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workflow_workflows',
            },
        ),
    ]
