import { CodeMouvementInfo, CodeMouvement } from '../types';

export const CODES_MOUVEMENT: Record<CodeMouvement, CodeMouvementInfo> = {
  // I - CAS DE CRÉATION (01-09)
  '01': {
    code: '01',
    libelle: 'Nomination Haut Emploi de l\'Etat (HEE) non fonctionnaire permanent',
    categorie: 'CREATION',
    description: 'Nomination à un poste de haut niveau pour un non-fonctionnaire permanent',
    documentsRequis: ['cv.pdf', 'diplomes.pdf', 'casier_judiciaire.pdf', 'certificat_medical.pdf', 'photo_identite.jpg'],
    rolesApprobateurs: ['DREN', 'MEN', 'FINANCE'],
    delaiTraitement: 30,
    heeType: 'NON_FONC_NON_PERM'
  },
  '02': {
    code: '02',
    libelle: 'Nomination d\'un Fonctionnaire',
    categorie: 'CREATION',
    description: 'Nomination d\'un agent au statut de fonctionnaire',
    documentsRequis: ['demande_nomination.pdf', 'diplomes.pdf', 'casier_judiciaire.pdf', 'certificat_medical.pdf', 'photo_identite.jpg'],
    rolesApprobateurs: ['DREN', 'MEN', 'FINANCE'],
    delaiTraitement: 45,
  },
  '03': {
    code: '03',
    libelle: 'Recrutement d\'un EFA',
    categorie: 'CREATION',
    description: 'Recrutement d\'un Elève Fonctionnaire Administratif',
    documentsRequis: ['demande_recrutement.pdf', 'diplomes.pdf', 'casier_judiciaire.pdf', 'certificat_medical.pdf', 'photo_identite.jpg'],
    rolesApprobateurs: ['DREN', 'MEN', 'FOP'],
    delaiTraitement: 30,
  },
  '04': {
    code: '04',
    libelle: 'Recrutement d\'un ELD',
    categorie: 'CREATION',
    description: 'Recrutement d\'un Elève de l\'Administration',
    documentsRequis: ['demande_recrutement.pdf', 'diplomes.pdf', 'casier_judiciaire.pdf', 'certificat_medical.pdf', 'photo_identite.jpg'],
    rolesApprobateurs: ['DREN', 'MEN', 'FOP'],
    delaiTraitement: 30,
  },
  '05': {
    code: '05',
    libelle: 'Nomination HEE fonctionnaire permanent',
    categorie: 'CREATION',
    description: 'Nomination HEE pour un fonctionnaire permanent',
    documentsRequis: ['arrete_nomination.pdf', 'cv.pdf', 'diplomes.pdf'],
    rolesApprobateurs: ['MEN', 'FINANCE'],
    delaiTraitement: 20,
    heeType: 'FONC'
  },
  '06': {
    code: '06',
    libelle: 'Nomination HEE fonctionnaire non permanent',
    categorie: 'CREATION',
    description: 'Nomination HEE pour un fonctionnaire non permanent',
    documentsRequis: ['arrete_nomination.pdf', 'cv.pdf', 'diplomes.pdf'],
    rolesApprobateurs: ['MEN', 'FINANCE'],
    delaiTraitement: 20,
    heeType: 'FONC_NON_PERM'
  },
  '07': {
    code: '07',
    libelle: 'Nomination HEE non fonctionnaire non permanent',
    categorie: 'CREATION',
    description: 'Nomination HEE pour un non-fonctionnaire non permanent',
    documentsRequis: ['arrete_nomination.pdf', 'cv.pdf', 'diplomes.pdf', 'contrat.pdf'],
    rolesApprobateurs: ['MEN', 'FINANCE'],
    delaiTraitement: 20,
    heeType: 'NON_FONC_NON_PERM'
  },
  '08': {
    code: '08',
    libelle: 'Rapatriement du personnel extérieur',
    categorie: 'CREATION',
    description: 'Retour et réintégration du personnel en poste à l\'étranger',
    documentsRequis: ['demande_rapatriement.pdf', 'attestation_service_exterieur.pdf', 'rapport_activite.pdf'],
    rolesApprobateurs: ['DREN', 'MEN', 'FINANCE'],
    delaiTraitement: 60,
  },
  '09': {
    code: '09',
    libelle: 'Autres nominations',
    categorie: 'CREATION',
    description: 'Autres cas de nomination non spécifiés',
    documentsRequis: ['demande_nomination.pdf', 'pieces_justificatives.pdf'],
    rolesApprobateurs: ['DREN', 'MEN'],
    delaiTraitement: 30,
  },

  // II - CAS DE MODIFICATION DE SITUATION (10-19)
  '10': {
    code: '10',
    libelle: 'Intégration',
    categorie: 'MODIFICATION',
    description: 'Intégration d\'un agent dans un corps ou cadre spécifique',
    documentsRequis: ['demande_integration.pdf', 'diplomes.pdf', 'attestation_service.pdf'],
    rolesApprobateurs: ['DREN', 'MEN'],
    delaiTraitement: 30,
  },
  '11': {
    code: '11',
    libelle: 'Titularisation',
    categorie: 'MODIFICATION',
    description: 'Passage d\'un agent stagiaire à titulaire',
    documentsRequis: ['rapport_stage.pdf', 'evaluation.pdf', 'demande_titularisation.pdf'],
    rolesApprobateurs: ['DREN', 'MEN'],
    delaiTraitement: 20,
  },
  '12': {
    code: '12',
    libelle: 'Avancement de Classe',
    categorie: 'MODIFICATION',
    description: 'Promotion à une classe supérieure (Avenant)',
    documentsRequis: ['avenant.pdf', 'evaluation.pdf', 'ancien_arrete.pdf'],
    rolesApprobateurs: ['DREN', 'MEN', 'FINANCE'],
    delaiTraitement: 15,
  },
  '13': {
    code: '13',
    libelle: 'Avancement d\'Echelon',
    categorie: 'MODIFICATION',
    description: 'Progression à l\'échelon supérieur',
    documentsRequis: ['arrete_avancement.pdf', 'evaluation.pdf'],
    rolesApprobateurs: ['DREN', 'MEN'],
    delaiTraitement: 10,
  },
  '14': {
    code: '14',
    libelle: 'Reclassement d\'un Fonctionnaire',
    categorie: 'MODIFICATION',
    description: 'Reclassement suite à concours ou diplôme (Arrêté)',
    documentsRequis: ['arrete_reclassement.pdf', 'diplomes.pdf', 'ancien_arrete.pdf'],
    rolesApprobateurs: ['MEN', 'FINANCE'],
    delaiTraitement: 25,
  },
  '15': {
    code: '15',
    libelle: 'Reclassement d\'un EFA ou d\'un ELD',
    categorie: 'MODIFICATION',
    description: 'Reclassement d\'élève fonctionnaire (Avenant)',
    documentsRequis: ['avenant.pdf', 'diplomes.pdf', 'certificat_scolarite.pdf'],
    rolesApprobateurs: ['DREN', 'MEN', 'FOP'],
    delaiTraitement: 20,
  },
  '16': {
    code: '16',
    libelle: 'Majoration de Salaire d\'un ELD',
    categorie: 'MODIFICATION',
    description: 'Augmentation de salaire pour un ELD',
    documentsRequis: ['demande_majoration.pdf', 'justificatif_anciennete.pdf'],
    rolesApprobateurs: ['DREN', 'FINANCE'],
    delaiTraitement: 15,
  },
  '17': {
    code: '17',
    libelle: 'Renouvellement de Contrat ou de Décision d\'engagement',
    categorie: 'MODIFICATION',
    description: 'Prolongation de contrat d\'engagement',
    documentsRequis: ['contrat_actuel.pdf', 'demande_renouvellement.pdf', 'evaluation.pdf'],
    rolesApprobateurs: ['DREN', 'MEN'],
    delaiTraitement: 15,
  },
  '18': {
    code: '18',
    libelle: 'Bonification d\'Ancienneté',
    categorie: 'MODIFICATION',
    description: 'Ajout d\'années d\'ancienneté',
    documentsRequis: ['demande_bonification.pdf', 'justificatifs_services.pdf'],
    rolesApprobateurs: ['DREN', 'MEN', 'FINANCE'],
    delaiTraitement: 20,
  },
  '19': {
    code: '19',
    libelle: 'Indemnité Compensatrice de congé non pris',
    categorie: 'MODIFICATION',
    description: 'Indemnisation des congés non utilisés',
    documentsRequis: ['demande_indemnite.pdf', 'releve_conges.pdf'],
    rolesApprobateurs: ['DREN', 'FINANCE'],
    delaiTraitement: 15,
    indemnites: ['542']
  },

  // III - POSITIONS DIVERSES (20-29)
  '20': {
    code: '20',
    libelle: 'Affectation',
    categorie: 'POSITION',
    description: 'Changement de localité d\'un fonctionnaire',
    documentsRequis: ['demande_affectation.pdf', 'accord_etablissement.pdf'],
    rolesApprobateurs: ['DREN', 'MEN'],
    delaiTraitement: 20,
  },
  '21': {
    code: '21',
    libelle: 'En Détachement',
    categorie: 'POSITION',
    description: 'Position de détachement auprès d\'une autre administration',
    documentsRequis: ['demande_detachement.pdf', 'accord_administration.pdf'],
    rolesApprobateurs: ['DREN', 'MEN', 'FINANCE'],
    delaiTraitement: 30,
  },
  '22': {
    code: '22',
    libelle: 'En Disponibilité',
    categorie: 'POSITION',
    description: 'Position de disponibilité (congé sans solde)',
    documentsRequis: ['demande_disponibilite.pdf', 'motif.pdf'],
    rolesApprobateurs: ['DREN', 'MEN'],
    delaiTraitement: 15,
  },
  '23': {
    code: '23',
    libelle: 'Position sous les Drapeaux',
    categorie: 'POSITION',
    description: 'Service militaire ou réserve',
    documentsRequis: ['ordre_appel.pdf', 'certificat_militaire.pdf'],
    rolesApprobateurs: ['DREN'],
    delaiTraitement: 10,
  },
  '24': {
    code: '24',
    libelle: 'Mis à la Disposition de la FOP',
    categorie: 'POSITION',
    description: 'Mise à disposition de la Formation Professionnelle',
    documentsRequis: ['demande_mise_disposition.pdf', 'accord_fop.pdf'],
    rolesApprobateurs: ['DREN', 'MEN', 'FOP'],
    delaiTraitement: 20,
  },
  '25': {
    code: '25',
    libelle: 'Régularisation d\'une Situation non statuée après 6 mois',
    categorie: 'POSITION',
    description: 'Régularisation après 6 mois sans statut',
    documentsRequis: ['rapport_situation.pdf', 'justificatifs.pdf'],
    rolesApprobateurs: ['DREN', 'MEN', 'FINANCE'],
    delaiTraitement: 30,
  },
  '26': {
    code: '26',
    libelle: 'Réintégration après Service Militaire',
    categorie: 'POSITION',
    description: 'Retour après service militaire',
    documentsRequis: ['demande_reintegration.pdf', 'certificat_fin_service.pdf'],
    rolesApprobateurs: ['DREN', 'MEN'],
    delaiTraitement: 15,
  },
  '27': {
    code: '27',
    libelle: 'Réintégration après Disponibilité',
    categorie: 'POSITION',
    description: 'Retour après disponibilité',
    documentsRequis: ['demande_reintegration.pdf', 'fin_disponibilite.pdf'],
    rolesApprobateurs: ['DREN', 'MEN'],
    delaiTraitement: 15,
  },
  '28': {
    code: '28',
    libelle: 'Réintégration après Suspension',
    categorie: 'POSITION',
    description: 'Retour après suspension de solde ou de fonction',
    documentsRequis: ['decision_reintegration.pdf', 'rapport_enquete.pdf'],
    rolesApprobateurs: ['DREN', 'MEN', 'FINANCE'],
    delaiTraitement: 20,
  },
  '29': {
    code: '29',
    libelle: 'Maintien en activité',
    categorie: 'POSITION',
    description: 'Prolongation d\'activité au-delà de la limite d\'âge',
    documentsRequis: ['demande_maintien.pdf', 'avis_medical.pdf'],
    rolesApprobateurs: ['MEN', 'FINANCE'],
    delaiTraitement: 25,
  },

  // IV - SANCTIONS (30-39)
  '30': {
    code: '30',
    libelle: 'Suspension de Solde',
    categorie: 'SANCTION',
    description: 'Suspension temporaire du salaire',
    documentsRequis: ['decision_suspension.pdf', 'rapport_disciplinaire.pdf'],
    rolesApprobateurs: ['DREN', 'MEN', 'FINANCE'],
    delaiTraitement: 10,
  },
  '31': {
    code: '31',
    libelle: 'Suspension de Fonction',
    categorie: 'SANCTION',
    description: 'Suspension temporaire des fonctions',
    documentsRequis: ['decision_suspension.pdf', 'rapport_disciplinaire.pdf'],
    rolesApprobateurs: ['DREN', 'MEN'],
    delaiTraitement: 10,
  },
  '32': {
    code: '32',
    libelle: 'Révocation avec Droits à pensions',
    categorie: 'SANCTION',
    description: 'Révocation avec conservation des droits à pension',
    documentsRequis: ['arrete_revocation.pdf', 'rapport_final.pdf'],
    rolesApprobateurs: ['MEN', 'FINANCE'],
    delaiTraitement: 30,
  },
  '33': {
    code: '33',
    libelle: 'Révocation sans Droits à pensions',
    categorie: 'SANCTION',
    description: 'Révocation sans conservation des droits à pension',
    documentsRequis: ['arrete_revocation.pdf', 'rapport_final.pdf'],
    rolesApprobateurs: ['MEN', 'FINANCE'],
    delaiTraitement: 30,
  },
  '34': {
    code: '34',
    libelle: 'Résiliation de Contrat/Décision d\'engagement',
    categorie: 'SANCTION',
    description: 'Rupture de contrat d\'engagement',
    documentsRequis: ['decision_resiliation.pdf', 'motif_resiliation.pdf'],
    rolesApprobateurs: ['DREN', 'MEN'],
    delaiTraitement: 15,
  },
  '35': {
    code: '35',
    libelle: 'Réduction d\'Ancienneté',
    categorie: 'SANCTION',
    description: 'Diminution de l\'ancienneté',
    documentsRequis: ['decision_reduction.pdf', 'rapport_disciplinaire.pdf'],
    rolesApprobateurs: ['DREN', 'MEN'],
    delaiTraitement: 15,
  },
  '36': {
    code: '36',
    libelle: 'Abaissement d\'Echelon',
    categorie: 'SANCTION',
    description: 'Descente à un échelon inférieur',
    documentsRequis: ['decision_abaissement.pdf', 'rapport_disciplinaire.pdf'],
    rolesApprobateurs: ['DREN', 'MEN'],
    delaiTraitement: 15,
  },
  '37': {
    code: '37',
    libelle: 'Rétrogradation',
    categorie: 'SANCTION',
    description: 'Descente à un grade inférieur',
    documentsRequis: ['decision_retrogradation.pdf', 'rapport_disciplinaire.pdf'],
    rolesApprobateurs: ['DREN', 'MEN'],
    delaiTraitement: 20,
  },
  '38': {
    code: '38',
    libelle: 'Redoublement de Stage',
    categorie: 'SANCTION',
    description: 'Répétition d\'une période de stage',
    documentsRequis: ['decision_redoublement.pdf', 'rapport_stage.pdf'],
    rolesApprobateurs: ['DREN', 'FOP'],
    delaiTraitement: 10,
  },
  '39': {
    code: '39',
    libelle: 'Redoublement d\'Echelon ou de Classe',
    categorie: 'SANCTION',
    description: 'Répétition d\'un échelon ou d\'une classe',
    documentsRequis: ['decision_redoublement.pdf', 'rapport_evaluation.pdf'],
    rolesApprobateurs: ['DREN', 'MEN'],
    delaiTraitement: 10,
  },

  // V - ANNULATION (40-49)
  '40': {
    code: '40',
    libelle: 'Décès',
    categorie: 'ANNULATION',
    description: 'Annulation suite au décès de l\'agent',
    documentsRequis: ['acte_deces.pdf', 'certificat_deces.pdf'],
    rolesApprobateurs: ['DREN', 'MEN', 'FINANCE'],
    delaiTraitement: 5,
  },
  '41': {
    code: '41',
    libelle: 'Démission',
    categorie: 'ANNULATION',
    description: 'Annulation suite à démission',
    documentsRequis: ['lettre_demission.pdf', 'accusé_reception.pdf'],
    rolesApprobateurs: ['DREN', 'MEN'],
    delaiTraitement: 15,
  },
  '42': {
    code: '42',
    libelle: 'En Retraite pour Limite d\'âge',
    categorie: 'ANNULATION',
    description: 'Départ à la retraite par limite d\'âge',
    documentsRequis: ['demande_retraite.pdf', 'acte_naissance.pdf'],
    rolesApprobateurs: ['DREN', 'MEN', 'FINANCE'],
    delaiTraitement: 30,
  },
  '43': {
    code: '43',
    libelle: 'En Retraite proportionnelle',
    categorie: 'ANNULATION',
    description: 'Départ à la retraite proportionnelle',
    documentsRequis: ['demande_retraite.pdf', 'releve_carriere.pdf'],
    rolesApprobateurs: ['DREN', 'MEN', 'FINANCE'],
    delaiTraitement: 30,
  },
  '44': {
    code: '44',
    libelle: 'En Retraite d\'office',
    categorie: 'ANNULATION',
    description: 'Mise à la retraite d\'office',
    documentsRequis: ['arrete_retraite.pdf', 'notification.pdf'],
    rolesApprobateurs: ['MEN', 'FINANCE'],
    delaiTraitement: 15,
  },
  '45': {
    code: '45',
    libelle: 'En Position Hors Cadre',
    categorie: 'ANNULATION',
    description: 'Passage en position hors cadre',
    documentsRequis: ['demande_hors_cadre.pdf', 'accord_administration.pdf'],
    rolesApprobateurs: ['DREN', 'MEN'],
    delaiTraitement: 20,
  },
  '46': {
    code: '46',
    libelle: 'Abrogation des Hauts Emplois pour non Fonctionnaires',
    categorie: 'ANNULATION',
    description: 'Suppression d\'un poste HEE pour non-fonctionnaire',
    documentsRequis: ['decision_abrogation.pdf', 'notification.pdf'],
    rolesApprobateurs: ['MEN', 'FINANCE'],
    delaiTraitement: 15,
  },
  '47': {
    code: '47',
    libelle: 'Opposition crédit',
    categorie: 'ANNULATION',
    description: 'Opposition sur le crédit (saisie, etc.)',
    documentsRequis: ['decision_opposition.pdf', 'document_juridique.pdf'],
    rolesApprobateurs: ['FINANCE'],
    delaiTraitement: 5,
  },
  '48': {
    code: '48',
    libelle: 'Annulation code rubrique',
    categorie: 'ANNULATION',
    description: 'Annulation de code rubrique (permanentes - doublons)',
    documentsRequis: ['demande_annulation.pdf', 'justificatif.pdf'],
    rolesApprobateurs: ['FINANCE'],
    delaiTraitement: 10,
  },
  '49': {
    code: '49',
    libelle: 'Abrogation des HEE Fonctionnaires',
    categorie: 'ANNULATION',
    description: 'Suppression d\'un poste HEE pour fonctionnaire',
    documentsRequis: ['decision_abrogation.pdf', 'notification.pdf'],
    rolesApprobateurs: ['MEN', 'FINANCE'],
    delaiTraitement: 15,
  },

  // VI - RÉGULARISATION (60-76)
  '60': {
    code: '60',
    libelle: 'Allocations familiales',
    categorie: 'REGULARISATION',
    description: 'Attribution ou modification d\'allocations familiales',
    documentsRequis: ['demande_allocations.pdf', 'actes_naissance_enfants.pdf'],
    rolesApprobateurs: ['DREN', 'FINANCE'],
    delaiTraitement: 15,
  },
  '61': {
    code: '61',
    libelle: 'Diverses Indemnités',
    categorie: 'REGULARISATION',
    description: 'Indemnités annuelles ou non permanentes',
    documentsRequis: ['demande_indemnites.pdf', 'justificatifs.pdf'],
    rolesApprobateurs: ['DREN', 'FINANCE'],
    delaiTraitement: 15,
    indemnites: ['542', '543']
  },
  '62': {
    code: '62',
    libelle: 'Diverses Retenues',
    categorie: 'REGULARISATION',
    description: 'Retenues non permanentes',
    documentsRequis: ['decision_retenue.pdf', 'justificatif.pdf'],
    rolesApprobateurs: ['FINANCE'],
    delaiTraitement: 10,
  },
  '63': {
    code: '63',
    libelle: 'Avance sur solde et Rappel de solde',
    categorie: 'REGULARISATION',
    description: 'Avance ou rappel de salaire',
    documentsRequis: ['demande_avance.pdf', 'justificatif_besoin.pdf'],
    rolesApprobateurs: ['DREN', 'FINANCE'],
    delaiTraitement: 10,
  },
  '64': {
    code: '64',
    libelle: 'Rappel différentiel trop perçu (indice)',
    categorie: 'REGULARISATION',
    description: 'Régularisation d\'un trop-perçu sur indice',
    documentsRequis: ['calcul_trop_percu.pdf', 'decision_regularisation.pdf'],
    rolesApprobateurs: ['FINANCE'],
    delaiTraitement: 15,
  },
  '65': {
    code: '65',
    libelle: 'Opposition Pension alimentaire',
    categorie: 'REGULARISATION',
    description: 'Opposition sur pension alimentaire',
    documentsRequis: ['decision_justice.pdf', 'notification.pdf'],
    rolesApprobateurs: ['FINANCE'],
    delaiTraitement: 5,
  },
  '66': {
    code: '66',
    libelle: 'Reversement trop perçu',
    categorie: 'REGULARISATION',
    description: 'Remboursement de solde indûment perçu',
    documentsRequis: ['calcul_reversement.pdf', 'accord_reversement.pdf'],
    rolesApprobateurs: ['FINANCE'],
    delaiTraitement: 15,
  },
  '67': {
    code: '67',
    libelle: 'Régularisation Indemnités moins perçues',
    categorie: 'REGULARISATION',
    description: 'Remboursement d\'indemnités non perçues',
    documentsRequis: ['calcul_indemnites.pdf', 'decision_regularisation.pdf'],
    rolesApprobateurs: ['FINANCE'],
    delaiTraitement: 15,
  },
  '68': {
    code: '68',
    libelle: 'Rappel différentiel moins perçu (indice)',
    categorie: 'REGULARISATION',
    description: 'Régularisation d\'un moins-perçu sur indice',
    documentsRequis: ['calcul_moins_percu.pdf', 'decision_regularisation.pdf'],
    rolesApprobateurs: ['FINANCE'],
    delaiTraitement: 15,
  },
  '69': {
    code: '69',
    libelle: 'Changement mode de paiement',
    categorie: 'REGULARISATION',
    description: 'Modification du mode de paiement',
    documentsRequis: ['demande_changement.pdf', 'rib.pdf'],
    rolesApprobateurs: ['FINANCE'],
    delaiTraitement: 5,
  },
  '70': {
    code: '70',
    libelle: 'Création code rubrique',
    categorie: 'REGULARISATION',
    description: 'Création d\'un code rubrique permanent jamais perçu',
    documentsRequis: ['demande_creation.pdf', 'justificatif.pdf'],
    rolesApprobateurs: ['FINANCE'],
    delaiTraitement: 10,
  },
  '71': {
    code: '71',
    libelle: 'Modification code rubrique',
    categorie: 'REGULARISATION',
    description: 'Modification d\'un code rubrique permanent',
    documentsRequis: ['demande_modification.pdf', 'justificatif.pdf'],
    rolesApprobateurs: ['FINANCE'],
    delaiTraitement: 10,
  },
  '72': {
    code: '72',
    libelle: 'Attribution numéro matricule d\'un élève fonctionnaire',
    categorie: 'REGULARISATION',
    description: 'Attribution d\'un numéro matricule',
    documentsRequis: ['demande_matricule.pdf', 'acte_naissance.pdf'],
    rolesApprobateurs: ['DREN', 'MEN'],
    delaiTraitement: 10,
  },
  '73': {
    code: '73',
    libelle: 'Affectation à l\'extérieur',
    categorie: 'REGULARISATION',
    description: 'Affectation hors de la fonction publique',
    documentsRequis: ['demande_affectation.pdf', 'accord_exterieur.pdf'],
    rolesApprobateurs: ['DREN', 'MEN'],
    delaiTraitement: 20,
  },
  '74': {
    code: '74',
    libelle: 'Diverses modifications',
    categorie: 'REGULARISATION',
    description: 'Modifications diverses (Matricule, Nom, etc.)',
    documentsRequis: ['demande_modification.pdf', 'justificatif_changement.pdf'],
    rolesApprobateurs: ['DREN', 'MEN'],
    delaiTraitement: 15,
  },
  '75': {
    code: '75',
    libelle: 'Déclassement',
    categorie: 'REGULARISATION',
    description: 'Descente de catégorie ou de classe',
    documentsRequis: ['decision_declassement.pdf', 'rapport.pdf'],
    rolesApprobateurs: ['DREN', 'MEN'],
    delaiTraitement: 20,
  },
  '76': {
    code: '76',
    libelle: 'Validation de service',
    categorie: 'REGULARISATION',
    description: 'Validation de services antérieurs',
    documentsRequis: ['demande_validation.pdf', 'justificatifs_services.pdf'],
    rolesApprobateurs: ['DREN', 'MEN'],
    delaiTraitement: 20,
  },

  // VII - CAS D'EXCLUSION (80-85)
  '80': {
    code: '80',
    libelle: 'Exclusion temporaire',
    categorie: 'EXCLUSION',
    description: 'Exclusion temporaire de la fonction publique',
    documentsRequis: ['decision_exclusion.pdf', 'rapport_disciplinaire.pdf'],
    rolesApprobateurs: ['DREN', 'MEN'],
    delaiTraitement: 10,
  },
  '81': {
    code: '81',
    libelle: 'Perte de la Nationalité Malagasy',
    categorie: 'EXCLUSION',
    description: 'Perte de la nationalité entraînant l\'exclusion',
    documentsRequis: ['decision_perte_nationalite.pdf', 'document_officiel.pdf'],
    rolesApprobateurs: ['DREN', 'MEN'],
    delaiTraitement: 15,
  },
  '82': {
    code: '82',
    libelle: 'Incarcération',
    categorie: 'EXCLUSION',
    description: 'Incarcération de l\'agent',
    documentsRequis: ['decision_incarceration.pdf', 'notification_justice.pdf'],
    rolesApprobateurs: ['DREN', 'MEN'],
    delaiTraitement: 5,
  },
  '83': {
    code: '83',
    libelle: 'Inaptitude définitive',
    categorie: 'EXCLUSION',
    description: 'Inaptitude définitive constatée médicalement',
    documentsRequis: ['certificat_medical_definitif.pdf', 'avis_commission.pdf'],
    rolesApprobateurs: ['DREN', 'MEN'],
    delaiTraitement: 20,
  },
  '84': {
    code: '84',
    libelle: 'Radiation',
    categorie: 'EXCLUSION',
    description: 'Radiation des effectifs',
    documentsRequis: ['decision_radiation.pdf', 'motif_radiation.pdf'],
    rolesApprobateurs: ['DREN', 'MEN'],
    delaiTraitement: 15,
  },
  '85': {
    code: '85',
    libelle: 'Double Emploi',
    categorie: 'EXCLUSION',
    description: 'Cumul d\'emplois non autorisé',
    documentsRequis: ['rapport_enquete.pdf', 'decision_regularisation.pdf'],
    rolesApprobateurs: ['DREN', 'MEN'],
    delaiTraitement: 20,
  },
};

// Notes manuscrites
export const NOTES_MANUSCRITES = {
  HAUT_EMPLOI_ETAT: {
    FONC: 0,
    NON_FONC: 1,
    FONC_NON_PERMANENT: 'A à J',
    NON_FONC_NON_PERMANENT: 'K à T'
  },
  INDEMNITES: {
    '542': 'Indemnité de Fonction d\'encadrement',
    '543': 'Indemnité de Fonction Spéciale'
  }
};

export const CATEGORIES = [
  { id: 'CREATION', label: 'Création', codes: ['01','02','03','04','05','06','07','08','09'] },
  { id: 'MODIFICATION', label: 'Modification', codes: ['10','11','12','13','14','15','16','17','18','19'] },
  { id: 'POSITION', label: 'Positions diverses', codes: ['20','21','22','23','24','25','26','27','28','29'] },
  { id: 'SANCTION', label: 'Sanctions', codes: ['30','31','32','33','34','35','36','37','38','39'] },
  { id: 'ANNULATION', label: 'Annulation', codes: ['40','41','42','43','44','45','46','47','48','49'] },
  { id: 'REGULARISATION', label: 'Régularisation', codes: ['60','61','62','63','64','65','66','67','68','69','70','71','72','73','74','75','76'] },
  { id: 'EXCLUSION', label: 'Exclusion', codes: ['80','81','82','83','84','85'] },
];

export const getCodeInfo = (code: string): CodeMouvementInfo | undefined => {
  return CODES_MOUVEMENT[code as CodeMouvement];
};

export const getDocumentsRequis = (code: string): string[] => {
  return CODES_MOUVEMENT[code as CodeMouvement]?.documentsRequis || [];
};

export const getRolesApprobateurs = (code: string): string[] => {
  return CODES_MOUVEMENT[code as CodeMouvement]?.rolesApprobateurs || [];
};

export const getCategorieFromCode = (code: string): string => {
  const categorie = CATEGORIES.find(cat => cat.codes.includes(code));
  return categorie?.label || 'Autre';
};