# Generated by Django 6.0.3 on 2026-03-04 08:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='date_derniere_action',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='etapes_validation',
            field=models.JSONField(default=dict, help_text='Historique des validations par étape'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='motif_rejet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiqueaction',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='etape_actuelle',
            field=models.CharField(choices=[('INTERESSE', 'Intéressé'), ('DREN', 'Direction Régionale'), ('MEN', 'Ministère Éducation Nationale'), ('FOP', 'Formation Professionnelle'), ('FINANCE', 'Finance'), ('TERMINE', 'Terminé'), ('REJETE', 'Rejeté')], default='INTERESSE', max_length=20),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='historiqueaction',
            name='action',
            field=models.CharField(choices=[('CREATION', 'Création'), ('VALIDATION', 'Validation'), ('REJET', 'Rejet'), ('TRANSFERT', 'Transfert'), ('MODIFICATION', 'Modification')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historiqueaction',
            name='etape',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='DossierData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='dossiers.dossier')),
            ],
            options={
                'db_table': 'dossiers_data',
            },
        ),
    ]
