# Generated by Django 6.0.3 on 2026-03-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0002_dossier_date_derniere_action_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iaanalyse',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='iaanalyse',
            name='classification',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='iaanalyse',
            name='score_risque',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
