# Generated by Django 6.0.3 on 2026-03-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0003_alter_iaanalyse_options_iaanalyse_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
