# Generated by Django 6.0.3 on 2026-03-12 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0004_dossier_date_cloture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='dossier',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='dossier',
            name='code_mouvement',
            field=models.CharField(blank=True, help_text="Code comme '01', '02', etc.", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='assigne_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_assignes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='etape_actuelle',
            field=models.CharField(choices=[('INTERESSE', 'Intéressé'), ('DREN', 'Direction Régionale'), ('MEN', 'Ministère Éducation Nationale'), ('FOP', 'Formation Professionnelle'), ('FINANCE', 'Finance'), ('TERMINE', 'Terminé')], default='INTERESSE', max_length=20),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='fonctionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='dossiers.fonctionnaire'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='motif_rejet',
            field=models.TextField(blank=True, help_text='Motif du rejet si le dossier a été rejeté', null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE_DREN', 'En attente DREN'), ('EN_ATTENTE_MEN', 'En attente MEN'), ('EN_ATTENTE_FOP', 'En attente FOP'), ('EN_ATTENTE_FINANCE', 'En attente Finance'), ('EN_COURS', 'En cours'), ('BLOQUE', 'Bloqué'), ('TERMINE', 'Terminé')], default='BROUILLON', max_length=20),
        ),
        migrations.AlterField(
            model_name='historiqueaction',
            name='action',
            field=models.CharField(choices=[('CREATION', 'Création'), ('VALIDATION', 'Validation'), ('REJET', 'Rejet'), ('TRANSFERT', 'Transfert'), ('MODIFICATION', 'Modification'), ('BLOQUAGE', 'Bloquage')], max_length=20),
        ),
        migrations.AlterField(
            model_name='iaanalyse',
            name='type_analyse',
            field=models.CharField(choices=[('RULE_BASED', 'Basé sur règles'), ('ML', 'Machine Learning')], max_length=20),
        ),
    ]
