# Generated by Django 6.0.3 on 2026-03-13 06:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0005_alter_document_options_alter_dossier_options_and_more'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['statut'], name='dossiers_do_statut_c317c6_idx'),
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['etape_actuelle'], name='dossiers_do_etape_a_675f54_idx'),
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['numero_dossier'], name='dossiers_do_numero__415484_idx'),
        ),
    ]
