# Generated by Django 6.0.3 on 2026-04-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0006_dossier_dossiers_do_statut_c317c6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='code_mouvement',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='etape_actuelle',
            field=models.CharField(choices=[('INTERESSE', 'Intéressé'), ('DREN', 'Direction Régionale'), ('MEN', 'Ministère Éducation Nationale'), ('FOP', 'Formation Professionnelle'), ('FINANCE', 'Finance'), ('TERMINE', 'Terminé'), ('REJETE', 'Rejeté')], default='INTERESSE', max_length=20),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='etapes_validation',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='motif_rejet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE_DREN', 'En attente DREN'), ('EN_ATTENTE_MEN', 'En attente MEN'), ('EN_ATTENTE_FOP', 'En attente FOP'), ('EN_ATTENTE_FINANCE', 'En attente Finance'), ('EN_COURS', 'En cours'), ('BLOQUE', 'Bloqué'), ('TERMINE', 'Terminé'), ('REJETE', 'Rejeté')], default='BROUILLON', max_length=20),
        ),
    ]
